apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istiod-istio-system
  namespace: istio-system
  labels:
    app: istiod
    release: istio
rules:
  - apiGroups:
      - networking.istio.io
    verbs:
      - create
    resources:
      - gateways
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - watch
      - list
      - update
      - delete